import { PortfolioData } from '../types/content';

export const portfolioContent: PortfolioData = {
  profile: {
    name: 'Emanuel Cruzat',
    role: 'A Graphic Designer and an Aspiring Data Engineer',
    bio: 'Combining Apple-inspired visual precision with modern data architecture to build calm, high-performance digital experiences.',
    portraitUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=800&q=80',
    portraitAlt: 'Portrait of Emanuel Cruzat',
    resumeUrl: 'https://docs.google.com/document/d/placeholder-resume',
    socials: {
      linkedin: 'https://linkedin.com/in/placeholder-emanuelcruzat',
      github: 'https://github.com/placeholder-emanuelcruzat',
      instagram: 'https://instagram.com/placeholder-emanuelcruzat',
      email: 'mailto:emanuel.cruzat@example.com',
    },
  },

  tools: [
    { name: 'Figma', category: 'design' },
    { name: 'Photoshop', category: 'design' },
    { name: 'Illustrator', category: 'design' },
    { name: 'InDesign', category: 'design' },
    { name: 'Python', category: 'data' },
    { name: 'SQL', category: 'data' },
    { name: 'PySpark', category: 'data' },
    { name: 'PostgreSQL', category: 'data' },
    { name: 'React', category: 'dev' },
    { name: 'TypeScript', category: 'dev' },
    { name: 'Vite', category: 'dev' },
    { name: 'Docker', category: 'dev' },
    { name: 'Git', category: 'dev' },
  ],

  experiences: [
    {
      id: 'exp-1',
      role: 'Lead Visual Designer',
      organization: 'Cruzat Design Studio',
      logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=120&q=80',
      logoAlt: 'Cruzat Design Studio Logo',
      year: '2024 — Present',
      description: 'Designing brand identities, typography systems, and digital visual experiences.',
    },
    {
      id: 'exp-2',
      role: 'Data Engineering Associate',
      organization: 'Data Insights Lab',
      logoUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=120&q=80',
      logoAlt: 'Data Insights Lab Logo',
      year: '2023 — 2024',
      description: 'Building automated SQL ETL pipelines and optimizing high-throughput data models.',
    },
    {
      id: 'exp-3',
      role: 'UI/UX & Graphics Specialist',
      organization: 'Freelance & Open Source',
      logoUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=120&q=80',
      logoAlt: 'Freelance Logo',
      year: '2022 — 2023',
      description: 'Crafting responsive user interfaces and visual assets for web applications.',
    },
  ],

  projects: [
    {
      id: 'gd-1',
      title: 'Oceanic Brand System',
      category: 'Graphic Design',
      year: '2024',
      imageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1000&q=80',
      imageAlt: 'Oceanic Brand System visual mockup',
      destinationUrl: 'https://github.com/placeholder-oceanic-brand',
      accentColor: '#0071e3',
      featured: true,
      tags: ['Branding', 'Typography', 'Visual Identity'],
      description: 'Minimalist brand identity exploring ocean blue palettes and grid structures.',
    },
    {
      id: 'gd-2',
      title: 'Minimalist Editorial Layout',
      category: 'Graphic Design',
      year: '2024',
      imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=80',
      imageAlt: 'Editorial print magazine layout preview',
      destinationUrl: 'https://github.com/placeholder-editorial-layout',
      accentColor: '#30b0fe',
      featured: false,
      tags: ['Print', 'Editorial', 'Grid'],
      description: 'System-first print editorial design focusing on optical font tracking and whitespace.',
    },
    {
      id: 'gd-3',
      title: 'Kinetic Poster Series',
      category: 'Graphic Design',
      year: '2023',
      imageUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=1000&q=80',
      imageAlt: 'Kinetic Poster Series artwork',
      destinationUrl: 'https://github.com/placeholder-poster-series',
      accentColor: '#00c6ff',
      featured: true,
      tags: ['Posters', 'Typography', 'Motion'],
      description: 'Experimental typographic poster exploration translating physical motion to 2D grids.',
    },
    {
      id: 'dev-1',
      title: 'Real-time Streaming Pipeline',
      category: 'Dev Project',
      year: '2024',
      imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1000&q=80',
      imageAlt: 'Data flow dashboard screenshot',
      destinationUrl: 'https://github.com/placeholder-data-pipeline',
      accentColor: '#2997ff',
      featured: true,
      tags: ['Python', 'PySpark', 'SQL', 'Docker'],
      description: 'Distributed event processing pipeline ingesting analytics metrics with sub-second latency.',
    },
    {
      id: 'dev-2',
      title: 'Apple-inspired Portfolio Engine',
      category: 'Dev Project',
      year: '2024',
      imageUrl: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=1000&q=80',
      imageAlt: 'Portfolio web app interface',
      destinationUrl: 'https://github.com/placeholder-portfolio-engine',
      accentColor: '#0071e3',
      featured: true,
      tags: ['React', 'TypeScript', 'Vite', 'CSS Modules'],
      description: 'High-performance static web application featuring translucent materials and fluid motion.',
    },
    {
      id: 'dev-3',
      title: 'ETL Pipeline Monitor',
      category: 'Dev Project',
      year: '2023',
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1000&q=80',
      imageAlt: 'ETL Monitor dashboard',
      destinationUrl: 'https://github.com/placeholder-etl-monitor',
      accentColor: '#34c759',
      featured: false,
      tags: ['SQL', 'PostgreSQL', 'Python'],
      description: 'Automated data validation and anomaly detection tool for relational databases.',
    },
  ],
};

export default portfolioContent;
